comment_homepage:
    path:     /comment
    defaults: { _controller: "ArusEntityCommentBundle:Default:index" }

comment_new:
    path:     /comment/new
    defaults: { _controller: "ArusEntityCommentBundle:Default:new" }
    methods:  [GET, POST]

comment_edit:
    path:     /comment/{id}/edit
    defaults: { _controller: "ArusEntityCommentBundle:Default:edit" }
    methods:  [GET, POST]

comment_delete:
    path:     /comment/{id}/delete
    defaults: { _controller: "ArusEntityCommentBundle:Default:delete" }
    methods:  DELETE

comment_getlist:
    path:     /comment/getlist/{entity_id}
    defaults: { _controller: "ArusEntityCommentBundle:Default:getList" }
    methods:  GET
