domain_homepage:
    path:     /domain
    defaults: { _controller: "ArusDomainBundle:Default:index" }

domain_export:
    path:     /domain/export
    defaults: { _controller: "ArusDomainBundle:Default:export" }
    methods:  [POST]

domain_show:
    path:     /domain/{id}/show
    defaults: { _controller: "ArusDomainBundle:Default:show" }
    methods:  [GET]

domain_view:
    path:     /domain/{id}/view
    defaults: { _controller: "ArusDomainBundle:Default:view" }
    methods:  [GET]

domain_add:
    path:     /domain/add/{project_id}
    defaults: { _controller: "ArusDomainBundle:Default:add", project_id:0 }
    methods:  [GET, POST]

domain_add_multiple:
    path:     /domain/addMultiple
    defaults: { _controller: "ArusDomainBundle:Default:addMultiple"}
    methods:  [POST]

domain_add_import:
    path:     /domain/addImport
    defaults: { _controller: "ArusDomainBundle:Default:addImport"}
    methods:  [POST]

domain_edit:
    path:     /domain/{id}/edit
    defaults: { _controller: "ArusDomainBundle:Default:edit" }
    methods:  [GET, POST]

domain_quickedit:
    path:     /domain/{id}/quickedit
    defaults: { _controller: "ArusDomainBundle:Default:quickedit" }
    methods:  [GET, POST]

domain_delete:
    path:     /domain/{id}/delete
    defaults: { _controller: "ArusDomainBundle:Default:delete" }
    methods:  [DELETE]

domain_survey:
    path:     /domain/{id}/survey
    defaults: { _controller: "ArusDomainBundle:Default:survey" }
    methods:  [GET, POST]
