loot_homepage:
    path:     /loot
    defaults: { _controller: "ArusEntityLootBundle:Default:index" }

loot_new:
    path:     /loot/new
    defaults: { _controller: "ArusEntityLootBundle:Default:new" }
    methods:  [GET, POST]

loot_edit:
    path:     /loot/{id}/edit
    defaults: { _controller: "ArusEntityLootBundle:Default:edit" }
    methods:  [GET, POST]

loot_unconfirm:
    path:     /loot/{id}/unconfirm
    defaults: { _controller: "ArusEntityLootBundle:Default:unconfirm" }
    methods:  POST

loot_confirm:
    path:     /loot/{id}/confirm
    defaults: { _controller: "ArusEntityLootBundle:Default:confirm" }
    methods:  POST

loot_delete:
    path:     /loot/{id}/delete
    defaults: { _controller: "ArusEntityLootBundle:Default:delete" }
    methods:  DELETE

loot_getlist:
    path:     /loot/getlist/{entity_id}
    defaults: { _controller: "ArusEntityLootBundle:Default:getList" }
    methods:  GET
