twig:
    globals:
        menu_extern:
            gitrob: ["Gitrob","http://127.0.0.1:9393/","github-alt"]
            10d: ["10degres","http://10degres.net","life-buoy"]

parameters:
    contact_email: g@10degres.net
    
    daemon_cluster_id: 0
    daemon_interpret_max_child: 10
    daemon_kill_max_child: 1
    daemon_run_max_child: 4
    daemon_run_task_priority: []
    daemon_run_task_ignore: [41]

    daemon:
        cluster:
            0: dev

    recon:
        project: [s3_buckets,gitrob,altgithub]
        server: [portscan_nc,srv_reco]
        domain: [whois,dnsrecon_axfr,dnsrecon_brute,theharvester,sublist3r,subthreat,crtsh]
        host: [host]
        request: [sqlmap_xss]
