# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    task:
        class: ArusTaskBundle\Controller\ServiceController
        arguments: [@doctrine.orm.default_entity_manager,@service_container,@router,@form.factory,@templating]
