server_homepage:
    path:     /server
    defaults: { _controller: "ArusServerBundle:Default:index" }

server_export:
    path:     /server/export
    defaults: { _controller: "ArusServerBundle:Default:export" }
    methods:  [POST]

server_show:
    path:     /server/{id}/show
    defaults: { _controller: "ArusServerBundle:Default:show" }
    methods:  [GET]

server_view:
    path:     /server/{id}/view
    defaults: { _controller: "ArusServerBundle:Default:view" }
    methods:  [GET]

server_add:
    path:     /server/add/{project_id}
    defaults: { _controller: "ArusServerBundle:Default:add", project_id:0 }
    methods:  [GET, POST]

server_add_multiple:
    path:     /server/addMultiple
    defaults: { _controller: "ArusServerBundle:Default:addMultiple"}
    methods:  [POST]

server_add_range:
    path:     /server/addRange
    defaults: { _controller: "ArusServerBundle:Default:addRange"}
    methods:  [POST]

server_add_import:
    path:     /server/addImport
    defaults: { _controller: "ArusServerBundle:Default:addImport"}
    methods:  [POST]

server_edit:
    path:     /server/{id}/edit
    defaults: { _controller: "ArusServerBundle:Default:edit" }
    methods:  [GET, POST]

server_quickedit:
    path:     /server/{id}/quickedit
    defaults: { _controller: "ArusServerBundle:Default:quickedit" }
    methods:  [GET, POST]

server_delete:
    path:     /server/{id}/delete
    defaults: { _controller: "ArusServerBundle:Default:delete" }
    methods:  DELETE
