requete_homepage:
    path:     /requete
    defaults: { _controller: "RequeteBundle:Default:index" }

requete_new:
    path:     /requete/new
    defaults: { _controller: "RequeteBundle:Default:new" }
    methods:  [GET, POST]

requete_import:
    path:     /requete/import/{project_id}
    defaults: { _controller: "RequeteBundle:Default:import", project_id: 0 }
    methods:  [GET, POST]

requete_edit:
    path:     /requete/{id}/edit
    defaults: { _controller: "RequeteBundle:Default:edit" }
    methods:  [GET, POST]

requete_delete:
    path:     /requete/{id}/delete
    defaults: { _controller: "RequeteBundle:Default:delete" }
    methods:  DELETE

requete_spliturl:
    path:     /requete/spliturl
    defaults: { _controller: "RequeteBundle:Default:splitUrl", _format:"json" }
    methods:  POST
